FROM postgres:12

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD ohhibitchitsme
ENV POSTGRES_DB postgres

ADD Postgres_DB_Backup.sql backup.sql
ADD pg_restore.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/pg_restore.sh

EXPOSE 5432/tcp
